# vim: set sw=2 et :

language: cpp

script:
  - $CXX_COMPILER --version
  - env CXX=$CXX_COMPILER CXXFLAGS=$CXX_FLAGS LDFLAGS=$CXX_LDFLAGS make

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc-9
      env:
        - CXX_COMPILER=g++

    - os: linux
      dist: focal
      compiler: clang-10
      addons:
        apt:
          packages:
            - clang-10
      env:
        - CXX_COMPILER=clang++-10

    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - CXX_COMPILER=clang++

